version: '3'
services:
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=123
    healthcheck:
      test: "exit 0"
  docker_test:
    build: ./app
    depends_on:
      - db
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh